[tool.poetry]
name = "slackchannels"
version = "0.1.0"
description = ""
authors = ["Ryu0n <hsung951027@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
openai = "^1.3.8"
slack-sdk = "^3.26.1"
fastapi = "^0.104.1"
uvicorn = "^0.24.0.post1"
pydantic = "^2.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
